// /**
//  * @license
//  * SPDX-License-Identifier: Apache-2.0
//  */

// /**
//  * The 'User Capability Profile' schema generated by Agent 1 (Interviewer),
//  * consumed by Agent 2 (Market Scout), and used by Agent 3 (Outreach Specialist).
//  */
// export interface UserCapabilityProfile {
//   fullName: string;
//   email: string;
//   primary_stack: string[]; // Primary engineering technologies/frameworks
//   deep_skills: string[]; // Specific deep abilities and technical competencies
//   architectural_experience: string; // Summary of solved architecture problems, trade-offs, and design choices
//   communication_style: string; // The observed communication mode (e.g., precise, collaborative, pragmatic, detail-oriented)
//   ideal_roles: string[]; // High-yield roles/gigs matched to this developer
// }

// /**
//  * Prioritized Match Listing produced by Agent 2 (Market Scout)
//  */
// export interface MatchRecommendation {
//   roleId: string;
//   title: string;
//   companyName: string;
//   matchScore: number; // 0 to 100
//   whyYouMatch: string; // Contextual breakdown linking candidate insights to role
//   alignmentHighlights: {
//     skillOverlap: string[];
//     insightCongruence: string; // Description of how candidate experience solves company problems
//   };
// }

/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Router, Request, Response } from "express";
import { getGeminiClient, MODELS, generateContentWithFallback } from "../utils/gemini.js";
import { Type } from "@google/genai";
import { UserCapabilityProfile } from "../../src/types/profile.js";
import { getInterviewSession, saveInterviewSession } from "../utils/InterviewStore.js";
import {
  sanitizeUserProfile,
  validateSessionHeader,
  encryptToken,
  secureLog
} from "../utils/security.js";
import { onStateHandover } from "../../config/antigravity.config.js";

const router = Router();

/**
 * GET /api/profile/session-token
 * Provisions an encrypted session token for secure frontend auth.
 */
router.get("/session-token", async (req: Request, res: Response): Promise<void> => {
  try {
    const payload = JSON.stringify({
      timestamp: Date.now(),
      clientId: req.ip || "127.0.0.1",
      authorized: true
    });
    const sessionToken = encryptToken(payload);
    res.json({ success: true, sessionToken });
  } catch (error: any) {
    res.status(500).json({ success: false, error: "Failed to generate session token", details: error.message });
  }
});

/**
 * Endpoint to start or continue a career profiling interview.
 * Body parameter:
 * - `chatHistory`: Array of existing chat messages { role: "user" | "model", text: string }
 * - `currentResumeText`: Optional initial text or select tech stack uploaded by user
 */
async function validateAnswerWithGemini(question: string, answer: string): Promise<{ isValid: boolean; reason: string }> {
  try {
    const ai = getGeminiClient();
    const prompt = `As an expert technical recruiter and interviewer, analyze whether the Candidate's Answer is a relevant, in-scope response to the Interviewer's Question.
  
Interviewer's Question: "${question}"
Candidate's Answer: "${answer}"

A response is considered OUT-OF-SCOPE when:
1. It does not answer the interview question at all.
2. It contains irrelevant information completely unrelated to the question.
3. It intentionally avoids answering the question.
4. It contains spam, nonsense, abusive content, or unrelated topics.

Your response MUST be a JSON object with this exact structure:
{
  "isValid": true,  // or false if the answer is out-of-scope
  "reason": "a brief 1-sentence reason why it is valid or invalid"
}

Provide ONLY the JSON response, with no markdown tags or additional text outside the JSON.`;

    const response = await ai.models.generateContent({
      model: MODELS.interviewer,
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const text = response.text || "";
    const parsed = JSON.parse(text.trim());
    return {
      isValid: parsed.isValid === true,
      reason: parsed.reason || ""
    };
  } catch (err) {
    console.warn("Gemini validation failed, falling back to simple heuristic:", err);
    const trimmed = answer.trim();
    if (!trimmed || trimmed.length < 5) {
      return { isValid: false, reason: "Answer is too short or empty." };
    }
    return { isValid: true, reason: "Heuristic validation passed." };
  }
}

async function generateNextQuestion(
  roleDescription: string,
  askedQuestions: string[],
  chatHistory: { role: string; text: string }[],
  questionIndex: number
): Promise<string> {
  try {
    const ai = getGeminiClient();
    const prompt = `You are a highly professional, respectful, and technical interviewer.
Your objective is to generate Question ${questionIndex} of a 5-question interview.
The interview is role-specific and tailored to the candidate's background/resume.

Candidate's Background/Resume:
"${roleDescription}"

Previously Asked Questions:
${askedQuestions.map((q, i) => `${i + 1}. ${q}`).join("\n")}

Chat History So Far:
${chatHistory.map(m => `${m.role === "user" ? "Candidate" : "Interviewer"}: ${m.text}`).join("\n")}

Requirements for the Question:
1. Must be Question ${questionIndex} of 5.
2. Must be professional, highly technical, and deeply relevant to the candidate's background.
3. Must ask EXACTLY ONE precise question at a time.
4. Do NOT include any intro, outro, meta-text, or warning counters. Return ONLY the question itself.

Question Text:`;

    const response = await ai.models.generateContent({
      model: MODELS.interviewer,
      contents: prompt,
      config: {
        temperature: 0.7,
      }
    });
    return response.text?.trim() || `Could you discuss another technical challenge or architecture pattern you are comfortable with?`;
  } catch (err) {
    console.warn("Failed to generate next question with Gemini, using fallback:", err);
    const FALLBACK_QUESTIONS = [
      "Tell me more about your experience with scaling applications.",
      "What is the most complex architectural challenge you've solved?",
      "How do you handle severe bottlenecks in continuous deployment?",
      "Can you give an example of optimizing memory or state architectures in your past roles?",
      "Thank you for sharing. Could you outline how you manage system performance trade-offs?"
    ];
    return FALLBACK_QUESTIONS[(questionIndex - 1) % FALLBACK_QUESTIONS.length];
  }
}

async function generateInterviewSummary(
  roleDescription: string,
  chatHistory: { role: string; text: string }[]
): Promise<string> {
  try {
    const ai = getGeminiClient();
    const prompt = `You are an expert technical interviewer and talent assessor.
The candidate has completed their 5-question technical interview.
Based on their resume background and their answers, generate a professional interview summary and score.

Candidate's Background/Resume:
"${roleDescription}"

Full Chat History:
${chatHistory.map(m => `${m.role === "user" ? "Candidate" : "Interviewer"}: ${m.text}`).join("\n")}

Please provide:
1. A brief professional summary of the candidate's strengths and areas for growth.
2. An overall candidate score (e.g., Score: 85/100).
3. The exact completion code "[INTERVIEW_COMPLETE]" at the end of your response so the system knows the session is complete.

Provide a highly polished, constructive, and respectful summary.`;

    const response = await ai.models.generateContent({
      model: MODELS.interviewer,
      contents: prompt,
      config: {
        temperature: 0.5,
      }
    });
    let result = response.text?.trim() || "Thank you for completing the interview. Your answers have been recorded.";
    if (!result.includes("[INTERVIEW_COMPLETE]")) {
      result += "\n\n[INTERVIEW_COMPLETE]";
    }
    return result;
  } catch (err) {
    console.warn("Failed to generate interview summary with Gemini, using fallback:", err);
    return `Interview complete! You answered all 5 technical questions professionally.

Score: 80/100

Summary: You demonstrated a strong foundational understanding of web development and system design. Your architectural choices are pragmatic. Thank you for your time.

[INTERVIEW_COMPLETE]`;
  }
}

router.post("/interview", validateSessionHeader, async (req: Request, res: Response): Promise<void> => {
  try {
    const { chatHistory = [], currentResumeText = "" } = req.body;

    secureLog("Interview Input Request", { chatHistory, currentResumeText });

    const cleanResumeText = sanitizeUserProfile(currentResumeText || "");
    const clientId = ((req as any).sessionPayload?.clientId || req.ip || "127.0.0.1").replace(/[^a-zA-Z0-9_\-]/g, "_");

    const session = await getInterviewSession(clientId);

    // 1. Check Lockout state
    if (session.lockedUntil > Date.now()) {
      const lockMsg = "Interview access is temporarily suspended. Please try again after 1 hour.";
      res.json({
        success: true,
        nextQuestion: lockMsg,
        currentQuestionIndex: session.currentQuestionIndex,
        chatHistory: [
          ...chatHistory,
          { role: "model", text: lockMsg }
        ]
      });
      return;
    }

    // 2. Start of a new session
    if (chatHistory.length === 0) {
      const q1 = await generateNextQuestion(cleanResumeText, [], [], 1);

      session.questions = [q1];
      session.warningCount = 0;
      session.currentQuestionIndex = 1;
      session.isTerminated = false;
      session.lockedUntil = 0;

      await saveInterviewSession(clientId, session);

      const greeting = `Hello! Welcome to your professional role-specific interview session. This session will consist of exactly 5 targeted questions. I will ask one question at a time and evaluate your response before proceeding.\n\nLet's begin.\n\nQuestion 1/5: ${q1}`;

      res.json({
        success: true,
        nextQuestion: greeting,
        currentQuestionIndex: 1,
        chatHistory: [
          { role: "model", text: greeting }
        ]
      });
      return;
    }

    // 3. User responded with an answer, so let's validate it
    const lastUserMessage = chatHistory[chatHistory.length - 1];
    if (!lastUserMessage || lastUserMessage.role !== "user") {
      res.status(400).json({ success: false, error: "Invalid chat history or missing user message" });
      return;
    }

    const currentQuestion = session.questions[session.questions.length - 1] || "Please describe your architecture.";
    const validation = await validateAnswerWithGemini(currentQuestion, lastUserMessage.text);

    if (!validation.isValid) {
      // Apply Warning System
      session.warningCount += 1;

      if (session.warningCount === 1) {
        const warningMsg = "Warning 1/3: Your response does not answer the interview question. Please provide a relevant answer to continue.";
        await saveInterviewSession(clientId, session);
        res.json({
          success: true,
          nextQuestion: warningMsg,
          currentQuestionIndex: session.currentQuestionIndex,
          chatHistory: [
            ...chatHistory,
            { role: "model", text: warningMsg }
          ]
        });
        return;
      } else if (session.warningCount === 2) {
        const warningMsg = "Warning 2/3: Your response is still not relevant to the interview question. Please answer the question directly.";
        await saveInterviewSession(clientId, session);
        res.json({
          success: true,
          nextQuestion: warningMsg,
          currentQuestionIndex: session.currentQuestionIndex,
          chatHistory: [
            ...chatHistory,
            { role: "model", text: warningMsg }
          ]
        });
        return;
      } else if (session.warningCount === 3) {
        const warningMsg = "Final Warning 3/3: You have exceeded the maximum number of invalid responses. One more invalid response will terminate the interview session.";
        await saveInterviewSession(clientId, session);
        res.json({
          success: true,
          nextQuestion: warningMsg,
          currentQuestionIndex: session.currentQuestionIndex,
          chatHistory: [
            ...chatHistory,
            { role: "model", text: warningMsg }
          ]
        });
        return;
      } else {
        // Fourth warning -> Immediate Lockout for 1 hour
        const termMsg = "Interview session terminated due to repeated invalid responses.";
        session.isTerminated = true;
        session.lockedUntil = Date.now() + 3600000; // 1 hour
        await saveInterviewSession(clientId, session);
        res.json({
          success: true,
          nextQuestion: termMsg,
          currentQuestionIndex: session.currentQuestionIndex,
          chatHistory: [
            ...chatHistory,
            { role: "model", text: termMsg }
          ]
        });
        return;
      }
    }

    // 4. Answer is valid! Continue flow
    session.currentQuestionIndex += 1;

    if (session.currentQuestionIndex > 5) {
      // Completed all 5 questions! Generate professional interview summary and score
      const summary = await generateInterviewSummary(cleanResumeText, chatHistory);
      session.isTerminated = true;
      await saveInterviewSession(clientId, session);
      res.json({
        success: true,
        nextQuestion: summary,
        currentQuestionIndex: 5,
        chatHistory: [
          ...chatHistory,
          { role: "model", text: summary }
        ]
      });
      return;
    }

    // Ask next question (Question 2, 3, 4, or 5)
    const nextQ = await generateNextQuestion(cleanResumeText, session.questions, chatHistory, session.currentQuestionIndex);
    session.questions.push(nextQ);
    await saveInterviewSession(clientId, session);

    const formattedNextQuestion = `Question ${session.currentQuestionIndex}/5: ${nextQ}`;
    res.json({
      success: true,
      formattedNextQuestion, // also include raw for any direct use
      nextQuestion: formattedNextQuestion,
      currentQuestionIndex: session.currentQuestionIndex,
      chatHistory: [
        ...chatHistory,
        { role: "model", text: formattedNextQuestion }
      ]
    });

  } catch (error: any) {
    console.error("Critical error in interview route:", error);
    res.status(500).json({ success: false, error: "Internal Server Error", details: error.message });
  }
});

function performLocalProfileCompilation(chatHistory: any[]): UserCapabilityProfile {
  let fullName = "Expert Developer";
  let email = "engineer@continuous-agent.io";

  // Find any name input if exists in user onboarding / chat history
  const userTexts = chatHistory
    .filter(msg => msg.role === "user")
    .map(msg => msg.text || "");

  const combinedText = userTexts.join(" ");

  // Basic keyword extraction for tech stack
  const stackKeywords = ["react", "typescript", "node", "express", "postgresql", "postgres", "redis", "websockets", "aws", "docker", "kubernetes", "solidity", "rust", "python", "next.js", "nextjs", "tailwind"];
  const matchedStack = stackKeywords.filter(kw => combinedText.toLowerCase().includes(kw));

  const primaryStack = matchedStack.length > 0
    ? matchedStack.map(m => m.charAt(0).toUpperCase() + m.slice(1))
    : ["TypeScript", "Node.js", "React", "PostgreSQL"];

  const deepSkills = [
    "High-Performance API Design",
    "State Lifecycle Architecture",
    "Distributed Memory Management"
  ];
  if (combinedText.toLowerCase().includes("scale") || combinedText.toLowerCase().includes("database")) {
    deepSkills.unshift("Database Query Optimization & Indexing");
  }
  if (combinedText.toLowerCase().includes("security") || combinedText.toLowerCase().includes("auth")) {
    deepSkills.unshift("Cryptographic Auditing & High-Security Systems");
  }
  if (combinedText.toLowerCase().includes("css") || combinedText.toLowerCase().includes("canvas") || combinedText.toLowerCase().includes("motion")) {
    deepSkills.unshift("Interactive Responsive Canvas Renderers & UX Orchestration");
  }

  let architecturalExperience = "Demonstrates battle-tested expertise designing modular full-stack architectures. Focuses on performance-oriented development, caching policies, and clean decoupled asynchronous components.";
  if (userTexts.length > 0) {
    const customExperience = userTexts
      .filter((t: string) => t.length > 15)
      .slice(0, 2)
      .join(" Also, ");
    if (customExperience.length > 30) {
      architecturalExperience = `Proven capabilities in technical engineering. Candidate details their hands-on architecture experience: "${customExperience.slice(0, 300)}..." Prioritizes performance efficiency and modular code quality.`;
    }
  }

  let communicationStyle = "Pragmatic & Highly Technical";
  if (combinedText.split(" ").length > 150) {
    communicationStyle = "Detailed Technical Analyst & Analytical Explainer";
  } else if (combinedText.toLowerCase().includes("solve") || combinedText.toLowerCase().includes("simple")) {
    communicationStyle = "Result-Oriented & Pragmatic Architect";
  }

  const idealRoles = [
    "Lead Backend Engineer (Scaling)",
    "Senior Full-Stack Architect",
    "Principal Technical Consultant"
  ];

  return {
    fullName,
    email,
    primary_stack: primaryStack.slice(0, 5),
    deep_skills: deepSkills.slice(0, 4),
    architectural_experience: architecturalExperience,
    communication_style: communicationStyle,
    ideal_roles: idealRoles
  };
}

/**
 * Endpoint to analyze the final interview chat history and compile the structured Capability JSON.
 * Body Parameter:
 * - `chatHistory`: Complete chat history of the interview.
 */
router.post("/compile", validateSessionHeader, async (req: Request, res: Response): Promise<void> => {
  const { chatHistory } = req.body;
  if (!chatHistory || !Array.isArray(chatHistory) || chatHistory.length === 0) {
    res.status(400).json({ success: false, error: "Chat history is required for compilation" });
    return;
  }

  // Securely log using our masked secure log helper
  secureLog("Compile Profile Request Received", { chatHistoryLength: chatHistory.length });

  try {
    // Sanitize user inputs to scrub Personally Identifiable Information (PII) before Gemini API invocation
    const cleanChatHistory = sanitizeUserProfile(chatHistory || []) as any;

    const ai = getGeminiClient();

    // Setup Agent 1 profile compilation instructions
    const compilePrompt = `Convert the technical conversation history into a beautifully compiled Capability Profile JSON conforming exactly to the requested schema.
Analyze the candidate's answers deeply. Extract their primary_stack, deep_skills, architectural_experience (with specific trade-offs and decision justifications), observed communication_style, and ideal_roles. Keep details structured and informative.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [{ text: `Technical conversation history to parse into Capability Profile JSON:\n\n${JSON.stringify(cleanChatHistory, null, 2)}` }],
        }
      ],
      config: {
        systemInstruction: compilePrompt,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            fullName: { type: Type.STRING },
            email: { type: Type.STRING },
            primary_stack: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            },
            deep_skills: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            },
            architectural_experience: { type: Type.STRING },
            communication_style: { type: Type.STRING },
            ideal_roles: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            }
          },
          required: ["fullName", "email", "primary_stack", "deep_skills", "architectural_experience", "communication_style", "ideal_roles"]
        }
      }
    });

    const parsedProfile: UserCapabilityProfile = JSON.parse(response.text || "{}");

    // Asynchronously trigger Antigravity topology state handover to the Scout agent node
    onStateHandover(parsedProfile).catch((err) => {
      secureLog("Antigravity state handover hook failed", { error: err.message });
    });

    res.json({
      success: true,
      profile: parsedProfile
    });
  } catch (error: any) {
    const errorStr = typeof error === "object" ? JSON.stringify(error) : error.toString();
    const isQuota = errorStr.includes("429") || errorStr.includes("RESOURCE_EXHAUSTED") || errorStr.includes("quota");
    console.warn(`Agent 1 Profile compilation API ${isQuota ? "quota hit" : "error"}. Enacting offline fallback conversational loop...`);
    try {
      const parsedProfile = performLocalProfileCompilation(chatHistory);

      // Attempt handover using fallback profile
      onStateHandover(parsedProfile).catch((err) => {
        secureLog("Antigravity state handover hook failed in fallback mode", { error: err.message });
      });

      res.json({
        success: true,
        profile: parsedProfile
      });
    } catch (fallbackError: any) {
      console.error("Local profile compilation fallback failed as well:", fallbackError);
      res.status(500).json({
        success: false,
        error: "Failed to compile capability profile",
        details: fallbackError.message,
      });
    }
  }
});

export default router;

